# Generated by Django 3.0.4 on 2020-04-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('linkedIn', models.CharField(default='null', max_length=150)),
                ('github', models.CharField(default='null', max_length=150)),
                ('position', models.CharField(choices=[('Python Developer', 'Python Developer'), ('Java Developer', 'Java Developer'), ('Web  Developer', 'Web Developer')], max_length=40)),
                ('available_date', models.DateField(default='now')),
            ],
        ),
    ]
