# Generated by Django 3.0.4 on 2020-04-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='available_date',
        ),
    ]
