# Generated by Django 3.0.4 on 2020-04-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_form', '0004_auto_20200402_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
